loading data
Begin training
fold: 1
Traceback (most recent call last):
  File "/mnt/c/Users/susan/git/HEA-Toxicity-Prediction/runner.py", line 139, in <module>
    train_loss = do_epoch_classify(model, device, train_loader, True, optimizer=optimizer)
  File "/mnt/c/Users/susan/git/HEA-Toxicity-Prediction/runner.py", line 98, in do_epoch_classify
    for input, output in dataloader:
  File "/home/susan/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/susan/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/susan/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/susan/.local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/c/Users/susan/git/HEA-Toxicity-Prediction/Data.py", line 32, in __getitem__
    return self.X[index], self.y[index]
AttributeError: 'Dataset' object has no attribute 'X'